### ISSUE TITLE
Redirect too many times

### ISSUE THREAD

**Issue by OutbackMatt** [palinkas-jo-reggelt/hMailServer_Log_Searcher#1]
I keep getting a 302 redirect from index.php back to itself.
Same response in multiple web browsers.

It happens in the login section, because if I remove the code about login in, then it works. May be only first issue of cookies that causes this.

There is a sub folder on my system "hMailServer\Logs\Problematic messages"
I get permission denied errors on items in that folder, but nothing in there in the last three years, so I just deleted them all, and the folder. It seems that the code wanted to open the folder as a file to read it's contents.

I had to increase my PHP variables extensively, to allow the script to used 2GB of Memory, and take upto 90 seconds, but it works well.

Even reads my custom log files.

**Comment by palinkas-jo-reggelt** [comment]
The redirect is intentional because of the cookie. There is an easy fix for that, but I was trying to be a smart-boy by keeping the whole code on one page. I'll fix that today. 

> There is a sub folder on my system "hMailServer\Logs\Problematic messages" I get permission denied errors on items in that folder, but nothing in there in the last three years, so I just deleted them all, and the folder. It seems that the code wanted to open the folder as a file to read it's contents.

I'll look into that too. It didn't attempt to read subfolders on my system.

> I had to increase my PHP variables extensively, to allow the script to used 2GB of Memory, and take upto 90 seconds, but it works well.

WOW 90 seconds! You must have a boat load of logs. I only keep 10 days worth of logs. For me its less than a second.

**Comment by OutbackMatt** [comment]
I ZIP logs at the end of each month, and it didn't read those (which is good), so I only have a months worth at most (30 days today)

I generate a heap of custom logs, one for each domain I manage and much more.
I like to track silly things like cipher used and stuff.

Searching for a client email address (that I host) today I get this
_9,090 results found among 235 files totalling 9.6 GB searched in 48.14 seconds_

Pretty busy server, more than 2000 messages per day

I might have to review how much I log. A single email to a non-hosted recipient cause 9 matches in the search.

**Comment by palinkas-jo-reggelt** [comment]
Well, I should have considered there might be cases with large logs. I should have a way of narrowing down the scope by log type or date or something. That's something I will add. I can eventually see this thing becoming sort of a replacement for the *doom* log parser. We'll see. That's something I've been thinking about. Since I "broke the code" from coax's admin log viewer, the rest of whatever I want to do is just work.

**Comment by palinkas-jo-reggelt** [comment]
> I keep getting a 302 redirect from index.php back to itself. Same response in multiple web browsers.

I split the logon (and other stuff) out of index.php and removed the redirect to index.php. Try it again and let me know if  you still have issues. Thanks.

**Comment by palinkas-jo-reggelt** [comment]
> I generate a heap of custom logs, one for each domain I manage and much more. I like to track silly things like cipher used and stuff.

You might like my php custom log. It logs all kinds of stuff to a database. Then if there's an event that I think is important enough, a  short link is generated and sent by SMS to my phone. The only issue is that its a real rube goldberg sort of thing and probably illegal anywhere except the data-wild-west USA, so I haven't put it up on github due to those issues. I can see all messages, train bayes, even drop them into the spam folder. Plus it records every single connection and logon attempt, among other things. And, of course, you can filter and search. It's helped me really dial in bayes.

**Comment by gotspatel** [comment]
We hope to see it in hms Forum sometime soon ;-)

Big Fan of your work

**Comment by OutbackMatt** [comment]
> We hope to see it in hms Forum sometime soon ;-)
> 
> Big Fan of your work

https://www.hmailserver.com/forum/viewtopic.php?f=9&t=40705

**Comment by OutbackMatt** [comment]
New version looks great - thanks
